name: Fix CNAME issues

on:
  workflow_run:
    workflows: [pages-build-deployment]
    types:
      - completed

jobs:
  fix_cname:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: gh-pages
      
      - name: Add CNAME file
        uses: "finnp/create-file-action@master"
        env:
          FILE_NAME: "CNAME"
          FILE_DATA: "scavhunt.uchicago.edu"
